apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: prediction-api
  name: prediction-api
  namespace: videobazaar
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: prediction-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prediction-api
    spec:
      containers:
      - image: reg.pegah.tech/brain/prediction-api:latest
        imagePullPolicy: IfNotPresent
        name: prediction-api
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: reg-pegah-credit
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: tapsell-servers
        operator: Exists

